apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-man-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pac-man
  template:
    metadata:
      labels:
        app: pac-man
    spec:
      containers:
      - name: pac-man
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pac-man-service
spec:
  selector:
    app: pac-man
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 8080
  type: NodePort
